### ISSUE TITLE
so3 sampling issues

### ISSUE THREAD

**Issue by fefei69** [HavenFeng/ArtEq#1]
Hi, 
When I tried to run your training sample code, I got 2 issues. 
First, I can't find `ArtEq/external/vgtk/vgtk/data/anchors/sphere12.ply` as needed in 
`ANCHOR_PATH = os.path.join(ROOT, 'data', 'anchors/sphere12.ply')`  
(in  [https://github.com/HavenFeng/ArtEq/blob/main/external/vgtk/vgtk/so3conv/functional.py](url) )

So I just copy the `sphere12.ply` from other repo [(https://github.com/dragonlong/equi-pose/blob/master/models/vgtk/data/anchors/sphere12.ply)](url)

Second, After using that `sphere12.ply` file I got another error in [https://github.com/HavenFeng/ArtEq/blob/main/external/vgtk/vgtk/functional/rotation.py](url) 

````
python src/train.py     --EPN_input_radius 0.4     --EPN_layer_num 2     --aug_type so3     --batch_size 2     --epochs 15     --gt_part_seg auto     --i 0     --kinematic_cond yes     --num_point 5000
adj_idx: [array([[4, 1, 5]]), array([[0, 2]]), array([[1, 3]]), array([[2, 4, 8]]), array([[0, 3, 9]]), array([[ 0, 10]]), array([[11, 12]]), array([[12, 13]]), array([[ 3, 14]]), array([[ 4, 10, 14]]), array([[ 9,  5, 15]]), array([[ 6, 16]]), array([[ 6,  7, 17]]), array([[ 7, 18]]), array([[ 9,  8, 19]]), array([[10, 19, 16]]), array([[11, 15, 17]]), array([[12, 16, 18]]), array([[13, 17, 19]]), array([[14, 15, 18]])]
Traceback (most recent call last):
File "/home/Desktop/ArtEq/external/vgtk/vgtk/functional/rotation.py", line 259, in icosahedron_so3_trimesh
R_adj = get_adjmatrix_trimesh(mesh, gsize)
File "/home/Desktop/ArtEq/external/vgtk/vgtk/functional/rotation.py", line 128, in get_adjmatrix_trimesh
face_adj =  np.vstack(adj_idx).astype(np.int32)
File "/home/anaconda3/envs/arteq/lib/python3.10/site-packages/numpy/core/shape_base.py", line 289, in vstack
return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2
````
It seems like that the dimensions of some array in adj_idx are wrong so that they can't be stacked vertically but I'm not sure if it is the mesh file issue or code issue. 

Thanks in advance!!

**Comment by mathXin112** [comment]
The same issue，looking forward to a reply！

**Comment by HavenFeng** [comment]
Hi, thanks for pointing it out, we are working on it now and will release an update soon, stay tuned!

**Comment by mathXin112** [comment]
----------------The message has been received，best wishes!您好，邮件已经收到，祝好。

**Comment by HavenFeng** [comment]
Just updated!

**Comment by mathXin112** [comment]
----------------The message has been received，best wishes!您好，邮件已经收到，祝好。
